### ISSUE TITLE
Cannot insert newline in function statement since suggestions pop up

### ISSUE THREAD

**Issue by manen** [vlang/vls#109]
When you declare a new function by typing, suggestions pop up, and when pressing enter to insert a newline, instead it puts in the first suggested function.

```v
// Typed: 
fn foo() {

// Expected:
fn foo() {

}

// Actual result:
fn foo() {compare_strings(a, b)} // compare_strings was the first that came up
```

Is this a VLS or extension issue, or is it my fault?

**Comment by nedpals** [comment]
Can't reproduce it now so it seems that it got fixed?
![image](https://user-images.githubusercontent.com/7358345/181906453-8c59aa8f-cd00-4357-bf21-0ef3cc704e8c.png)

**Comment by manen** [comment]
i won't be home for another few days so i can't check but i don't remember it being an issue lately so i guess so
