### ISSUE TITLE
VLS is constantly crashing.

### ISSUE THREAD

**Issue by manen** [vlang/vls#111]
VLS is very unstable.

The biggest issue I found is that I can't finish typing my function/type/struct/variable because VLS will crash immediately.

I think VLS should (at least for now) handle errors completely softly. If anything bad happens, print it to vls.log, and leave it be.

**Comment by nedpals** [comment]
@manen Please take note that:

> VLS is a work-in-progress, pre-alpha language server. It may not be guaranteed to work reliably on your system due to memory management issues and other factors.

In order for VLS to stabilize, we need information such as the code you use and the system information so that we can fix it here.

**Comment by nedpals** [comment]
> I think VLS should (at least for now) handle errors completely softly. If anything bad happens, print it to vls.log, and leave it be.
Your concern has been fixed here: https://github.com/vlang/vls/commit/b1090848d16d30183d78095361d0299825f88360. But still, I need the information mentioned above to address your issue.

**Comment by manen** [comment]
> we need information such as the code you use and the system information so that we can fix it here.

Okay!
`v doctor`:
```
OS: linux, "Arch Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 2600 Six-Core Processor
CC version: cc (GCC) 10.2.0

getwd: /home/manen
vmodules: /home/manen/.vmodules
vroot: /opt/v
vexe: /opt/v/v
vexe mtime: 2021-04-20 18:29:55
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 bd539b6

Git version: git version 2.31.1
Git vroot status: weekly.2021.16-9-gbd539b64 (10 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

> Your concern has been fixed here: [b109084](https://github.com/vlang/vls/commit/b1090848d16d30183d78095361d0299825f88360). But still, I need the information mentioned above to address your issue.

Hmm, I think the VSCode extension installed VLS just yesterday. Oh well, I'll try updating.

There were quite a few errors that were like `This is a V compiler error.`. If I catch them again I'll make sure to send them over

**Comment by manen** [comment]
![image](https://user-images.githubusercontent.com/49951816/115667776-bd552480-a335-11eb-9840-062efe61e27f.png)

**Comment by nedpals** [comment]
@manen Can you try post the contents of the file that VLS tried to parse? Seems like an issue in checker that needs to be fixed.

**Comment by manen** [comment]
Here's my log:
```
[Info  - 3:46:51 PM] VLS Version: 0.0.1, OS: linux 64
[Info  - 3:46:51 PM] Client / Editor: Visual Studio Code 1.55.2
V panic: string.eq(): nil string
v hash: bd539b6
                                                        | 0x563792236cad | /home/manen/.vls/bin/vls(+0x98cad) 
                                                        | 0x56379228077f | /home/manen/.vls/bin/vls(+0xe277f) 
                                                        | 0x563792225ba3 | /home/manen/.vls/bin/vls(+0x87ba3) 
                                                        | 0x563792227c15 | /home/manen/.vls/bin/vls(+0x89c15) 
                                                        | 0x5637922809ab | /home/manen/.vls/bin/vls(+0xe29ab) 
                                                        | 0x563792285d28 | /home/manen/.vls/bin/vls(+0xe7d28) 
                                                        | 0x563792287dbc | /home/manen/.vls/bin/vls(+0xe9dbc) 
                                                        | 0x5637922370b4 | /home/manen/.vls/bin/vls(+0x990b4) 
                                                        | 0x56379221a3ed | /home/manen/.vls/bin/vls(+0x7c3ed) 
                                                        | 0x563792238ac9 | /home/manen/.vls/bin/vls(+0x9aac9) 
                                                        | 0x56379223d020 | /home/manen/.vls/bin/vls(+0x9f020) 
                                                        | 0x5637922411cd | /home/manen/.vls/bin/vls(+0xa31cd) 
                                                        | 0x5637921b2872 | /home/manen/.vls/bin/vls(+0x14872) 
                                                        | 0x563792240140 | /home/manen/.vls/bin/vls(+0xa2140) 
                                                        | 0x5637921a03be | /home/manen/.vls/bin/vls(+0x23be) 
                                                        | 0x7f3bdb959b25 | /usr/lib/libc.so.6(__libc_start_main+0xd5) 
                                                        | 0x5637921a03fe | /home/manen/.vls/bin/vls(+0x23fe) 
[Info  - 3:46:52 PM] Connection to server got closed. Server will restart.
[Error - 3:46:52 PM] Request textDocument/completion failed.
```

I'm pretty sure it's the same as #113 (string.eq(): nil string), so the example HarryET gave should apply here too.
