### ISSUE TITLE
vraylib not showing suggestions

### ISSUE THREAD

**Issue by nedpals** [vlang/vls#112]
> Hi, I'm not getting Intellisense on waotzi's vraylib module (can't get a list of modules and types by triggering autocomplete), is it just a thing VLS or the VSCode extension can't do, or is it something I did wrong? When I type out the full function name, VLS understands it and provides argument types and all, but it's still a big big bummer.

Module: https://github.com/MajorHard/vraylib

Code:
```
module main

import waotzi.vraylib as rl

fn main() {
    rl.// nothing
}
```

**Comment by medvednikov** [comment]
@nedpals why not planned?

**Comment by nedpals** [comment]
I assumed that the module used a lot of features which broke on the recent versions of V hence "not planned" in a sense of "cannot reproduce" it. But seeing that it worked properly, these should be closed as "completed" instead.

![image](https://user-images.githubusercontent.com/7358345/181906339-bf5fef07-fc38-4a0f-9f49-be2d80f987a8.png)

**Comment by medvednikov** [comment]
Great :)
