### ISSUE TITLE
Error during build: unexpected name `bool`, expecting `(`

### ISSUE THREAD

**Issue by acisternino** [vlang/vls#139]
I have followed the instructions for building VLS without any modification and the compiler fails at the `v cmd/vls ` stage.

Log:

```sh
✔ ~/development/github-ext/vls [use-tree-sitter|✔]
09:39 $ git pull
Already up to date.

✔ ~/development/github-ext/vls [use-tree-sitter|✔]
09:39 $ v cmd/vls
vls/vls.v:60:8: error: unexpected name `bool`, expecting `(`
   58 |
   59 | interface ReceiveSender {
   60 |     debug bool
      |           ~~~~
   61 |     send(data string)
   62 |     receive() ?string

✔ ~/development/github-ext/vls [use-tree-sitter|✔]
09:39 $ v version
V 0.2.2 46cdf4f
```

**Comment by nedpals** [comment]
@acisternino  Lots of changes in V since the version you've used. Please `v up` or manually git pull your V installation to get to the latest version.

**Comment by acisternino** [comment]
OK, thanks a lot.

I am sorry but ATM I just can't work with the tip of the development branch. 

v0.2.2 is what comes with Homebrew and was easy enough to install. I'll postpone my experiment once the situation stabilizes.
