### ISSUE TITLE
Failed installing VLS

### ISSUE THREAD

**Issue by Hunam6** [vlang/vls#140]
check the checkbox
![image](https://user-images.githubusercontent.com/38606542/122931621-57a10b00-d36d-11eb-9ba3-e26c2077c729.png)
click on "Yes"
![image](https://user-images.githubusercontent.com/38606542/122931668-625ba000-d36d-11eb-8497-84eb996423ce.png)

**Comment by doamatto** [comment]
> ![image](https://user-images.githubusercontent.com/38606542/123188222-f3c93000-d49b-11eb-9630-ef061027062f.png)
> #138
> 
> Do you have an idea @doamatto?

Looks like you're on the latest branch, not master. Make sure to checkout the right branch (`git checkout master` and `git pull` before building)

**Comment by Hunam6** [comment]
@nedpals
![image](https://user-images.githubusercontent.com/38606542/123337013-ee74ef80-d546-11eb-8a93-eb731aebf79c.png)

**Comment by nedpals** [comment]
@Hunam6 just follow @doamatto's advice. The new branch isn't ready for use yet.

**Comment by nedpals** [comment]
I have moved the tree-sitter V folder inside VLS so it should not be a problem anymore to install it.
