### ISSUE TITLE
document symbol and workspace symbol support

### ISSUE THREAD

**Issue by nedpals** [vlang/vls#142]
textDocument/documentSymbol: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_documentSymbol

workspace/symbol: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_symbol

Previous implementation: https://github.com/vlang/vls/pull/43

**Comment by ylluminarious** [comment]
@nedpals Please see this PR: https://github.com/vlang/vls/pull/146
