### ISSUE TITLE
VLS Fails to locate modules in backwards directories `..`

### ISSUE THREAD

**Issue by carterisonline** [vlang/vls#143]
VLS Seems to be able to locate modules in the current working directory, as well as from V itself and `~/.vmodules`, but cannot locate modules backwards (relative to the file that's being edited)

#### From `cmd/vls/main.v`:

![image](https://user-images.githubusercontent.com/39879966/124698439-7abfd480-deae-11eb-8135-53b5deaad7f0.png)
> when running `v .` in the `./cmd/vls` directory, V seems to be able to locate the `vls` module two modules backwards, but VLS cannot do the same.

## Steps to reproduce
1. Install the `vscode-vlang` extention for VSCode
2. Clone this repository (tree and latest commit listed below)
3. Compile using `v cmd/vls`
4. Set these settings in `settings.json` (for vscode):
```json
"v.vls.enable": true,
"v.vls.customPath": "<repo location>/cmd/vls/vls"
```
5. Open the vls repository in VSCode `code <repo location>`

> on branch `use-tree-sitter`
> on commit `25b1f98bf0916b92f3faed76357d14dc4c468638`

**Comment by nedpals** [comment]
@carterisonline Thanks for reporting. I forgot to add the workspace path as an import path :sweat_smile:
