### ISSUE TITLE
vls does not compile (treesitter branch)

### ISSUE THREAD

**Issue by despiegk** [vlang/vls#154]
```
despiegk@kristofgouna vls % v -gc boehm cmd/vls
vls/vls.v:296:7: error: select key: `<-` operator expected
  294 |                 ls.is_typing = a != 0
  295 |             }
  296 |             50 * time.millisecond {
      |                ^
  297 |                 if !ls.is_typing {
  298 |                     continue
```

seems

**Comment by despiegk** [comment]
false alarm was on wrong branch

**Comment by despiegk** [comment]
needs to be

```
			> 50 * time.millisecond {
```

but cannot save, the autoformat removes

**Comment by JalonSolov** [comment]
Need to update your V.  That was just changed in a recent commit so the `>` is not needed.

**Comment by nedpals** [comment]
Unrelated to the issue but there is also an issue with the analyzer with the new [grammar rewrite](https://github.com/nedpals/tree-sitter-v/pull/8) merged yesterday so I'll be pushing the fixes for the rewrite in a minute

**Comment by nedpals** [comment]
> Unrelated to the issue but there is also an issue with the analyzer analyzing the stuff from the new [grammar rewrite](https://github.com/nedpals/tree-sitter-v/pull/8) merged yesterday so I'll be pushing the fixes in a minute

Merged in https://github.com/vlang/vls/commit/f3372045593fe1a324e20a80f8f90bd9edbee267.
