### ISSUE TITLE
Built-in modules not found on Windows

### ISSUE THREAD

**Issue by MrWheatley** [vlang/vls#186]
Using the latest version of V, VLS, and the VSCode extension.
![image](https://user-images.githubusercontent.com/28412095/131430034-3fd0288a-5657-4a3e-8820-2ffa686d44eb.png)

v doctor:
![image](https://user-images.githubusercontent.com/28412095/131430420-4979f021-b26d-42dc-8298-b592f18d133a.png)

**Comment by yuyi98** [comment]
vscode-vlang:  
```
V › Vls: Custom Vroot Path
Custom path to the V installation directory (VROOT).
```
Please set empty and try (it will use the system setting).

**Comment by nedpals** [comment]
@MrWheatley try @yuyi98 's suggestion first and if not, can you show to us a screenshot of the output tab? (Open command palette by pressing Control + Shift + P -> Select "Output: Focus on Output View" -> select "V Language Server" at the output dropdown)

**Comment by MrWheatley** [comment]
After setting the vroot to empty this appeared:
![image](https://user-images.githubusercontent.com/28412095/131493943-d76c35c2-4f0f-4a70-8b71-a64e459cb68b.png)

and this is the output:
![image](https://user-images.githubusercontent.com/28412095/131493972-7d20fe24-66be-4afd-9c04-def158aa7001.png)

I also enabled the debug option and this happened:
![image](https://user-images.githubusercontent.com/28412095/131494019-9b225e56-3abb-43bd-9dd8-ae3d14caa3bb.png)

**Comment by yuyi98** [comment]
It's a bug.
Please set the Path environment variable so that v.exe can run anywhere.

**Comment by MrWheatley** [comment]
Yup that worked.
It's kinda weird how v adds C:\v\.bin to the path, but not C:\v

**Comment by yuyi98** [comment]
This is really a bug.

**Comment by nedpals** [comment]
We'll open this issue until it is fixed. Thanks for your report!
