### ISSUE TITLE
[BUG] AutoCompletion adds struct preview when defining sum-type

### ISSUE THREAD

**Issue by Mondanzo** [vlang/vls#189]
When defining a sum-type vls autocompletes the structs adding all the parameters for the struct making it more effort to write a sum-type with vls than without it. Same happens when using a struct as a type in a function.

**Comment by nedpals** [comment]
@Mondanzo can you provide any screenshots and code that we can reproduce this problem?

**Comment by Mondanzo** [comment]
Because it's an autocomplete bug I attached a gif. I hope this works out
![danzo_1630469536-b78otEkLmS](https://user-images.githubusercontent.com/14519085/131610610-4b231384-8235-4d9e-9df5-f9085d1fa081.gif)

**Comment by nedpals** [comment]
@Mondanzo thats more than enough. Thanks 🙂

**Comment by nedpals** [comment]
Fixed in https://github.com/vlang/vls/issues/189#:~:text=init%20snippets%20(%23189)-,488f45c,-Write
