### ISSUE TITLE
Building error with jsonrpc

### ISSUE THREAD

**Issue by Nukiloco** [vlang/vls#232]
```
> Building VLS...
server\diagnostics.v:3:1: builder error: bad module definition: C:\Users\User\.vmodules\vls\server\diagnostics.v imports module "vls.jsonrpc" but C:\Users\User\.vmodules\vls\jsonrpc\jsonrpc.v is defined as module `jsonrpc`
    1 | module server
    2 |
    3 | import jsonrpc
      | ~~~~~~~~~~~~~~
    4 | import lsp
    5 | import term
Failed building VLS
```

**Comment by Nukiloco** [comment]
From the looks of it, this might be a Vlang error actually since I installed vls into .vmodules.

**Comment by Nukiloco** [comment]
Yea just installed it into a folder right next to where Vlang is installed and it didn't error out, so this is an issue with installing it in .vmodules though I just got another issue now.

**Comment by JalonSolov** [comment]
Yes, the "modules bug" has been around for a while.  The way it is usually worked around is to clone the module somewhere else, then create a link in .vmodules pointing to the actual location.

That way everything works.

**Comment by Nukiloco** [comment]
I moved VLS into a folder called VlangVLS right beside the folder where Vlang is installed just to fix this issue.
