### ISSUE TITLE
Typing println does not show up on the auto complete list

### ISSUE THREAD

**Issue by Nukiloco** [vlang/vls#263]
## Problem Description

I created a new vlang project and typed in ``println`` though nothing appears at all

## Expected Output

``println`` should appear

## Actual Output

``println`` does not appear

## Steps to Reproduce

type ``println`` anywhere

**Comment by nedpals** [comment]
@Nukiloco Can you show the VSCode output of the V Language Server? It should show the location of your V folder (VROOT).

Builtin types and functions won't show if VLS cannot detect the V installation directory.

**Comment by Nukiloco** [comment]
> 
> 
> @Nukiloco Can you show the VSCode output of the V Language Server? It should show the location of your V folder (VROOT).
> 
> Builtin types and functions won't show if VLS cannot detect the V installation directory.

I just set the installation directory just now.
Upon doing this though, after restarting vls and vscode, ``println`` is still not showing up.

![orlcVqe3k6](https://user-images.githubusercontent.com/16618467/140912697-30f1df72-4afc-4b5e-919a-1afad9a313ec.png)

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
