### ISSUE TITLE
void_sym evaluated but not used

### ISSUE THREAD

**Issue by creepinson** [vlang/vls#267]
### V doctor
```
OS: linux, "Arch Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 2600 Six-Core Processor
CC version: cc (GCC) 11.1.0

getwd: /home/theo/dev/vls
vmodules: /home/theo/.vmodules
vroot: /usr/lib/vlang
vexe: /usr/lib/vlang/v
vexe mtime: 2021-11-03 03:00:44
is vroot writable: false
is vmodules writable: true
V full version: V 0.2.4 b72a2de

Git version: git version 2.33.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 333c14de-dirty
```

## Problem Description

I tried to compile vls from source with the following commands from the readme...

```zsh
git clone https://github.com/vlang/vls && cd vls
v run build.vsh clang
```

It fails to build with the error described below. I have clang version 12.0.1.

## Expected Output

Binary compiled according to the readme.

## Actual Output

![image](https://user-images.githubusercontent.com/11761863/140843264-3e147747-18b3-46e8-b7a1-8a1c1a627e56.png)

> v -gc boehm -keepc -cg -cc clang cmd/vls -o /home/theo/dev/vls/bin/vls
analyzer/symbol_registration.v:159:84: error: `void_sym` evaluated but not used
  157 |     field_type_node := field_decl_node.child_by_field_name('type')
  158 |     field_name_node := field_decl_node.child_by_field_name('name')
  159 |     field_sym := sr.store.find_symbol_by_type_node(field_type_node, sr.src_text) or { void_sym }

## Steps to Reproduce

```zsh
git clone https://github.com/vlang/vls && cd vls
v run build.vsh clang
```

**Comment by nedpals** [comment]
@creepinson Your version of V is outdated. Update V first and try compiling it again.

**Comment by creepinson** [comment]
That seems to have been the problem, thanks 👍🏼 
I was using an outdated AUR package, compiling V from source fixed it.
