### ISSUE TITLE
Allow for __global usage

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/vls#270]
Currently vls reports diagnostic error messages when the code uses the __global statement.
I suggest either adding `-enable-globals` to `mut p := ls.launch_v_tool('-enable-globals', '-shared', '-check', input_path)` in general or implementing a way to disable this check.

**Comment by Ekopalypse** [comment]
... and that revealed that globals are not really handled yet. Files containing the global variables but don't declare them are reported with undefined identifier diagnostics.

**Comment by nedpals** [comment]
We can add the check in the meantime but it will be enabled in the future once the on-demand diagnostics are fully implemented. Will implement it right now. Thanks @Ekopalypse !
