### ISSUE TITLE
not start VLS - mac OS M1 and vscode-vlang extension 0.1.11

### ISSUE THREAD

**Issue by richardazevedo** [vlang/vls#272]
a update de vscode extension, but keep with the same trouble.

[vls_report_1637330585.md](https://github.com/vlang/vscode-vlang/files/7570845/vls_report_1637330585.md)

**Comment by nedpals** [comment]
This is not an issue with vscode-vlang so I thought of moving it here.

@richardazevedo Upon reading the error, are you developing a V project inside a cloud drive?

**Comment by richardazevedo** [comment]
> This is not an issue with vscode-vlang so I thought of moving it here.
> 
> @richardazevedo Upon reading the error, are you developing a V project inside a cloud drive?

Yeah, inside a icloud drive, only my tests.

**Comment by nedpals** [comment]
I see, thanks!
