### ISSUE TITLE
Trigger Parameter Hints not work

### ISSUE THREAD

**Issue by boris-741** [vlang/vls#282]
Ctrl+Shift+Space	editor.action.triggerParameterHints not work for last vls server ( 24.11.21 )
but on mouse hover I see the information I nee
![func_info](https://user-images.githubusercontent.com/8223870/143296029-91728a7a-dcd5-493f-ad1b-fbed272e2cbd.jpg)
d

**Comment by nedpals** [comment]
Hi, thanks for reporting this. As of this moment, the signature help feature has a very simplified implementation so this issue makes me wanna delve into this further. 😄
