### ISSUE TITLE
Support `$tmpl` Lint.

### ISSUE THREAD

**Issue by KeitoTobi1** [vlang/vls#289]

**Comment by nedpals** [comment]
Hi, are you referring to support for analyzing generics?

**Comment by KeitoTobi1** [comment]
Yes.

**Comment by nedpals** [comment]
Oh. Definitely it will be implemented in the soonest time 😃

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
