### ISSUE TITLE
After VSCode is closed, VLS procs do not stop and become CPU hoggers

### ISSUE THREAD

**Issue by dxps** [vlang/vls#293]
### V doctor
```
OS: linux, Pop!_OS 21.04
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
CC version: cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

getwd: /home/dxps/dev/dxps_gh/vlang_playground/vweb_hello_world
vmodules: /home/dxps/.vmodules
vroot: /home/dxps/apps/v
vexe: /home/dxps/apps/v/v
vexe mtime: 2021-12-11 19:24:23
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 fe14e2f

Git version: git version 2.30.2
Git vroot status: weekly.2021.48-78-gfe14e2fc (4 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```

### VLS info 
```
vls version 0.0.1.d7a7c11
```

## Problem Description

As described in the previous #292 issue, as code completion stops working, I close (not restart) VSCode.
The two VLS processes remain active and one of them starts hogging the CPU (and system fan kicks in, ofc):
```shell
$ ps -ef | grep vls | grep -v grep
dxps      454832    1872 12 21:36 ?        00:05:28 /home/dxps/apps/bin/vls --debug=false
dxps      454840  454832  0 21:36 ?        00:00:03 /home/dxps/apps/bin/vls --child --enable  --disable  --debug --vroot
$ 
```
Here is an `htop` sample:

![image](https://user-images.githubusercontent.com/14140226/145690633-8c623bea-944d-4380-9c3b-4d6168506259.png)

The only option that I have and use is to run `killall` on them.

Thanks.

**Comment by dxps** [comment]
Tested with the latest version, compiled from source, that is `vls version 0.0.1.9bbb6a9`.

I just open VSCode in that simple repo. As you can see, no `.v` is open, just the Settings window (that opens from the last VSCode session):

![image](https://user-images.githubusercontent.com/14140226/145701669-d740f430-65e8-4471-9daf-9d4252d8888c.png)

Closing VSCode, and the VLS processes are still running, with the main one consuming some CPU cores:

![image](https://user-images.githubusercontent.com/14140226/145701807-8f096e94-e159-41b1-9583-95eba7f3cc49.png)

**Comment by nedpals** [comment]
I'll reopen this issue for the problems regarding CPU usage after inactivity.
