### ISSUE TITLE
Connection problems in Emacs lsp-mode

### ISSUE THREAD

**Issue by nedpals** [vlang/vls#298]
### VLS info 
```
vls version: 0.0.1.7ac8c72
```

## Problem Description
There's a problem connecting VLS to Emacs' [lsp-mode](https://emacs-lsp.github.io/lsp-mode/).

## Expected Output

Connected and initialized properly.

## Actual Output

Hangs when entering `initialize` phase.

## Steps to Reproduce
Must install [v-mode](https://github.com/damon-kwok/v-mode) and [lsp-mode](https://emacs-lsp.github.io/lsp-mode/) packages first before using VLS on Emacs. 

`init.el`
```elisp
(add-to-list 'auto-mode-alist '("\\(\\.v?v\\|\\.vsh\\)$" . v-mode))

(with-eval-after-load 'lsp-mode
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-stdio-connection '("<path-to-vls>"))
    :major-modes '(v-mode)
    :server-id 'v-ls))

  (add-hook! 'v-mode-hook #'lsp))
```

For connecting via TCP

```elisp
(add-to-list 'auto-mode-alist '("\\(\\.v?v\\|\\.vsh\\)$" . v-mode))

(defun lsp-v-server-start-fun (port)
  `("~/.vmodules/bin/vls" "--socket" "--port" ,(number-to-string port)))

(with-eval-after-load 'lsp-mode
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-tcp-connection 'lsp-v-server-start-fun)
    :major-modes '(v-mode)
    :server-id 'v-ls))

  (add-hook! 'v-mode-hook #'lsp))
```

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
