### ISSUE TITLE
VLS Exited with Status Code 139 on Sublime

### ISSUE THREAD

**Issue by nac5604** [vlang/vls#301]
### V doctor
```
OS: windows, Microsoft Windows 10 Home v19044 64-bit
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 9 4900HS with Radeon Graphics
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\Users\user
vmodules: C:\Users\user\.vmodules
vroot: C:\Users\user\v
vexe: C:\Users\user\v\v.exe
vexe mtime: 2022-01-11 20:57:30
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 ab642ca

Git version: git version 2.34.1.windows.1
Git vroot status: weekly.2022.02-14-gab642cac
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 9de1a49e
```

### VLS info 
```
vls version 0.0.1.7ac8c72
```

## Problem Description
Tried to edit [this code](https://gist.github.com/nac5604/439f8a93fbf6ae49e5673b069eb86f05), but Sublime text responded with [this error window](https://imgur.com/aQZJAqh).

## Expected Output
VLS and Sublime should properly provide suggestions from V.

## Actual Output
Sublime displays [this error window](https://imgur.com/aQZJAqh).

## Steps to Reproduce
Edit some V code in Sublime Stable 4126 with LSP 4070-1.15.0 installed and configured with VLS 0.0.1.7ac8c72.

## Last Recorded LSP Requests
[vls.log](https://gist.github.com/nac5604/4d8daee84b8aca3d282e685fc7311bbc)

**Comment by kendfss** [comment]
Your gist seems to be private. Could you make it public please?  
According to [this](https://tldp.org/LDP/abs/html/exitcodes.html) it's fatal error signal 11.  

Sorry I can't be more help, that's all I know about it.  

I am wondering though, are you using/have you written any of an LSP package for sublime?  
I've been trying to use vls with Sublime but (apart from one time when I created a fixed length array and it declared that the `os`, `flag`, and `clipboard` packages couldn't be found - but `math` could... and then it removed the errors when I saved the file - without having to do anything to my file/module/path) it does nothing beyond initialize.  
Whenever I explicitly call the format command, it says "file does not exist" in the status bar and nothing else seems to happen.

**Comment by SirZenith** [comment]
I think this problem might be caused by URI handling error in VLS. Latest pull request fixes this problem, if you'd like to, you can try update VLS.

I would like to hear your feedback.

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
