### ISSUE TITLE
vs code extension not working on macos

### ISSUE THREAD

**Issue by aditya1944** [vlang/vls#309]
[vls_report_1645123809.md](https://github.com/vlang/vscode-vlang/files/8095312/vls_report_1645123809.md)
[vls_report_1645125562.md](https://github.com/vlang/vscode-vlang/files/8095313/vls_report_1645125562.md)
[vls_report_1645171977.md](https://github.com/vlang/vscode-vlang/files/8095314/vls_report_1645171977.md)

**Comment by nedpals** [comment]
@aditya1944  Just a followup, have you tried updating VLS? If not, you may download the prebuilt binaries [here](https://github.com/vlang/vls/releases/latest) and follow these [steps](https://github.com/vlang/vls#vscode-vscodium-and-other-derivatives). Thanks 🙂
