### ISSUE TITLE
Folding not worrking with vscode

### ISSUE THREAD

**Issue by MElborolossy** [vlang/vls#310]
### V doctor
```
OS: linux, Ubuntu 20.04.4 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/mohammed/.vmodules/threefoldtech/rmb/msgbusd
vmodules: /home/mohammed/.vmodules
vroot: /home/mohammed/Documents/v
vexe: /home/mohammed/Documents/v/v
vexe mtime: 2022-02-18 21:33:18
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 f8b8950.4cdb244

Git version: git version 2.25.1
Git vroot status: weekly.2022.07-45-g4cdb2441 (27 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8
```

### VLS info 
```
vls version 0.0.1.e4ae12f
```

## Problem Description

Folding not working with VSCode, when I disable it, default VSCode folding works, and it is fine for me.

## Expected Output

Folding working without problem.

## Actual Output

Folding not working.

## Steps to Reproduce

- Open VSCode on any v project and vls enabled
- Folding not working
- Add `folding_range` to disable features OR close vls.
- Folding works fine

**Comment by nedpals** [comment]
@MElborolossy Just a followup, have you tried updating VLS? If not, you may download the prebuilt binaries [here](https://github.com/vlang/vls/releases/latest) and follow these [steps](https://github.com/vlang/vls#vscode-vscodium-and-other-derivatives). Thanks 🙂

**Comment by MElborolossy** [comment]
I know that vls still in development phase, but it still crash, auto-complete not good enough, goto function or variable work randomly.
Kindly, vls needs a lot of work to be usable.

**Comment by nedpals** [comment]
Thank you for your feedback. Your concerns are valid and they contribute to the stability of VLS. 

I will be closing this issue since https://github.com/vlang/vls/commit/2fe3f734d9615cb7c5eb8001ed5b24e6f7cb3c2a has fixed this which I tried.
