### ISSUE TITLE
array `.map` and `.filter`methods not appearing in autocomplete

### ISSUE THREAD

**Issue by Sarctiann** [vlang/vls#326]
Arrays methods `.map` `.filter` and all others that implements `it`
this methods have a placeholder in builtin [Look here](https://github.com/vlang/v/blob/9355048b6c37d04b961bcc06b32746b37f873e4c/vlib/builtin/array.v#L683) 

## should be a way to get to include them on the autocomplete suggestions

**Comment by Krotki** [comment]
I briefly looked into it and symbols are not created for those function. Will try to narrow it down later today.

**Comment by cli-ish** [comment]
autocomplete is also missing for these array functions:
`clone` `clone` `any` `all` `repeat` `repeat` `prepend` `trim` `clear` `delete_many` `delete` `delete_last` `first` `last` `pop` `reverse` `reverse_in_place` `join`

See https://github.com/vlang/v/blob/master/doc/docs.md#arrays

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
