### ISSUE TITLE
Wont Compile

### ISSUE THREAD

**Issue by Moncheeta** [vlang/vls#327]
## System Information
I'm running Manjaro Linux.

### V doctor
OS: linux, "Manjaro Linux"
Processor: 6 cpus, 64bit, little endian, Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
CC version: cc (GCC) 11.2.0

getwd: /home/moncheeta/Downloads/vls
vmodules: /home/moncheeta/.vmodules
vroot: /usr/lib/vlang
vexe: /usr/lib/vlang/v
vexe mtime: 2022-04-27 01:27:06
is vroot writable: false
is vmodules writable: true
V full version: V 0.2.4 b72a2de

Git version: git version 2.35.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 333c14de-dirty

### VLS info 
I can't compile from source using the git repo. But, here's my vlang version.
V 0.2.4 b72a2de

## Problem Description
I can't compile vls, because I get this error.

## Expected Output
It's supposed to create a binary.

## Actual Output
$ v run build.vsh gcc
> Building VLS...
v -g -gc boehm -keepc -cc gcc cmd/vls -o /home/moncheeta/Downloads/vls/bin/vls
analyzer/symbol_registration.v:173:84: error: `void_sym` evaluated but not used
  171 | fn (mut sr SymbolAnalyzer) struct_field_decl(field_access SymbolAccess, field_decl_node C.TSNode) ?&Symbol {
  172 |     field_type_node := field_decl_node.child_by_field_name('type') ?
  173 |     field_sym := sr.store.find_symbol_by_type_node(field_type_node, sr.src_text) or { void_sym }
      |                                                                                       ~~~~~~~~
  174 |     field_name_node := field_decl_node.child_by_field_name('name') or {
  175 |         // struct embedding
Failed building VLS

## Steps to Reproduce
Clone the vlang/vls repo, "cd vls", and run "v run build.vsh gcc".

**Comment by JalonSolov** [comment]
That is a positively _ancient_ version of V (from Aug 30, 2021).  You'll definitely need to update to the latest version if you want to compile vls.

If you installed the AUR version, that's why.

You'll be a lot happier with V by removing what you have, and installing using these instructions:  https://github.com/vlang/v#installing-v---from-source-preferred-method

Yes, I know this works as I'm also on Manjaro, with latest version of V, and vls compiles fine for me.

**Comment by Moncheeta** [comment]
That worked. I didn't know that the AUR version was out of date.
