### ISSUE TITLE
Installing vls from vscode does not work

### ISSUE THREAD

**Issue by nassah221** [vlang/vls#328]
## System Information
Windows 11

### VLS Error 
```
Error: Command failed: v -prod -o C:\Users\hassa\.vls\bin\vls.exe cmd/vls
Note: tcc is not recommended for -prod builds
failed thirdparty object build cmd:
"C:\Users\hassa\v\thirdparty\tcc\tcc.exe"   -std=c99 -D_DEFAULT_SOURCE -O2 -DNDEBUG  -I "C:\Users\hassa\.vls\tree_sitter\lib" -o "C:\Users\hassa\.vmodules\cache\98\98631fe4e3fa6233a44d2390f4181f76.o" -c "C:\Users\hassa\.vls\tree_sitter\lib\lib.c" 
builder error: In file included from C:/Users/hassa/.vls/tree_sitter/lib/lib.c:14:

C:/Users/hassa/.vls/tree_sitter/lib/./stack.c:274: error: ';' expected (got "StackSliceArray")
```

## Problem Description
I installed Vlang. Downloaded the vscode Vlang extension, created a .v file. Enabled vls from the extension settings then vscode prompted to install vls upon which it failed and the error output is mentioned above.

## Steps to Reproduce

1. Install v
2. Download the vls vscode extension
3. Enable vls from the extension settings
4. Create a .v file and open it in vscode
5. Install vls on vscode prompt

**Comment by angel-git** [comment]
On mac m1 enabling the VLS on visual studio fails with:

```
Error: Command failed: v -prod -o /Users/agavalda/.vls/bin/vls cmd/vls
analyzer/symbol_registration.v:173:84: error: `void_sym` evaluated but not used
  171 | fn (mut sr SymbolAnalyzer) struct_field_decl(field_access SymbolAccess, field_decl_node C.TSNode) ?&Symbol {
  172 |     field_type_node := field_decl_node.child_by_field_name('type') ?
  173 |     field_sym := sr.store.find_symbol_by_type_node(field_type_node, sr.src_text) or { void_sym }
      |                                                                                       ~~~~~~~~
  174 |     field_name_node := field_decl_node.child_by_field_name('name') or {
  175 |         // struct embedding

```

**Comment by nedpals** [comment]
@nassah221 I suggest you use our daily builds here in the meantime: https://github.com/vlang/vls/releases

@angel-git Please submit a separate issue. Thanks

**Comment by nedpals** [comment]
Closing this as this should've been fixed in the latest version of vscode-vlang : https://github.com/vlang/vscode-vlang/commit/a9cc6b7f5f19d22d4299d43c49c03be4e6a329e4
