### ISSUE TITLE
Doesn't work on Windows. Infinite loading.

### ISSUE THREAD

**Issue by offbrok** [vlang/vls#337]
### V doctor
```
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: Error: exec failed (CreateProcess) with code 2: Не удается найти указанный файл.
 cmd: cc --version

getwd: C:\Users\offbr
vmodules: C:\Users\offbr\.vmodules
vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2022-05-30 12:34:35
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 a3c0a9b.844ba2a

Git version: git version 2.27.0.windows.1
Git vroot status: weekly.2022.21-40-g844ba2a1 (54 commit(s) behind V master)
.git/config present: true
thirdparty/tcc: N/A
```

### VLS info 
```
vls version 0.0.1.3675028
```

## Problem Description
Doesn't work on Windows.
Endless loading of autocomplete.

## Actual Output
Infinite loading.
![image](https://user-images.githubusercontent.com/25367108/172048557-b50b1af7-3e7d-4e58-97f3-ca1e1362bd5c.png)

**Comment by nedpals** [comment]
Hi. A user have experienced a similar issue to this and have pushed https://github.com/vlang/vls/commit/95b446e8b4f3a7723de285dc177eede7a2238f31. Would love to know if the issue still persists. Thanks 😃

**Comment by offbrok** [comment]
Okay, I'll check it out the other day and give you feedback.

**Comment by offbrok** [comment]
@nedpals I checked. Problem solved, thank you.
