### ISSUE TITLE
Can not Go to method and auto import

### ISSUE THREAD

**Issue by ddkwork** [vlang/vls#339]
![Screenshot_20220606_093300_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/19886504/172080324-479df910-c3d2-4fa0-b998-fee0891f2593.jpg)

**Comment by nedpals** [comment]
@ddkwork hi! can you provide a better image for this? github always times out upon serving the image. thanks!

**Comment by nedpals** [comment]
as for auto import, this is currently not yet supported.

**Comment by ddkwork** [comment]
> as for auto import, this is currently not yet supported.

Ok, thank you. And  how to debug v code?
