### ISSUE TITLE
Crash reports destination

### ISSUE THREAD

**Issue by varholak-peter** [vlang/vls#340]
The crash report logs are currently dumped into the home directory, however that creates quite a clutter.
Ideally they'd be put in a place where they make logical sense without the need to use the User directory directly.

My proposals would be one of:
- `/home/.vls/logs` or `/home/.vls/crash_reports`
- `/var/log/vls` - this is a pretty idiomatic place to store logs

I don't have much Windows experience but I believe putting logs in local app data folder seems reasonable. This comes with one drawback which is the fact that app data folder is not very user accessible, but I think that tools such as `v doctor` could help with that by pretty printing reports.

**Comment by nedpals** [comment]
Thanks for the concern 😃  it is indeed a clutter and putting it into a folder would make more sense. As for the location your proposal of `<home dir>/.vls/crash_reports` makes much more sense since It would be very easy to find compared to the alternatives. We'll do this today.
