### ISSUE TITLE
VLS can't compile

### ISSUE THREAD

**Issue by iambudi** [vlang/vls#35]
V 0.2 a2cd1b1 on Big Sur

```bash
git clone https://github.com/nedpals/vls2.git vls && cd vls/
v -prod cmd/vls
```

> lsp/signature_help.v:36:12: error: cannot register struct `lsp.SignatureInformation`, another type with this name exists
>    34 | }
>    35 |
>    36 | pub struct SignatureInformation {
>       |            ~~~~~~~~~~~~~~~~~~~~
>    37 | pub mut:
>    38 |     label string

**Comment by nedpals** [comment]
@iambudi You should clone `https://github.com/vlang/vls.git` instead of `https://github.com/nedpals2/vls2.git` Will update the readme :)
