### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by Zymlex** [vlang/vls#36]
![изображение](https://user-images.githubusercontent.com/25817412/102978167-d00a4900-454f-11eb-9acf-150595044e94.png)

v doctor
OS: windows, Microsoft Windows Server 2019 Datacenter v17763 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
CC version: N/A

vroot: D:\SW\Dev\V
vexe: D:\SW\Dev\V\v.exe
vexe mtime: 2020-12-23 08:59:48
is vroot writable: true
V full version: V 0.1.29 6ad5ecf.0c987f4

Git version: git version 2.29.1.windows.1
Git vroot status: latest-commit-124-g0c987f43 (797 commit(s) behind V master)
.git/config present: true
thirdparty/tcc: N/A

**Comment by medvednikov** [comment]
Old V.
