### ISSUE TITLE
High cpu and ram consumption

### ISSUE THREAD

**Issue by AndreMenew** [vlang/vls#360]
### V doctor
```
OS: windows,  v
Processor: 8 cpus, 64bit, little endian, Error: exec failed (CreateProcess) with code 2: O sistema não pode encontrar o arquivo especificado.
 cmd: wmic cpu get name /format:table
CC version: Error: exec failed (CreateProcess) with code 2: O sistema não pode encontrar o arquivo especificado.
 cmd: cc --version

getwd: C:\v\vls\bin
vmodules: C:\Users\AndreLuiz\.vmodules
vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2022-07-02 03:33:15
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 5b97ad1

Git version: git version 2.36.0.windows.1
Git vroot status: weekly.2022.26-28-g5b97ad15
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2
```

### VLS info 
```
vls version 0.0.1.f764ed3
```

## Problem Description
The system is consuming too much memory and power.

## Expected Output

Low resource consumption.

## Actual Output

<h3> <a href="https://anonfiles.com/t31chaucyf/vls_log">vls.log</a> </h3>

![vls](https://user-images.githubusercontent.com/95880914/176986568-2a3be753-026b-44fd-ba6b-a993aca3b16a.gif)

**Comment by asampal** [comment]
I'm also seeing this in Windows with the CI-built vls executable. 

![image](https://user-images.githubusercontent.com/281639/177075299-174a15b9-9af0-42f9-9f3c-69e65970e9ad.png)

**Comment by asampal** [comment]
Some additional info:

When I enable/disable the language server debug mode there's an error notification.

![image](https://user-images.githubusercontent.com/281639/177078278-ada4a94e-8c58-4e4e-88e0-639b70abbb88.png)

This happens despite the language server running (see the extension's output, above).

**Comment by nedpals** [comment]
i just installed the Windows Performance Recorder on my windows vm which i can confirm. will try to resolve this issue immediately

![image](https://user-images.githubusercontent.com/7358345/177082849-6d6d31d8-c191-4d99-adf7-e70fdc51ebf5.png)

**Comment by nedpals** [comment]
Result after d5db5b7

![Screenshot 2022-07-05 142205 after d5db5b7](https://user-images.githubusercontent.com/7358345/177264543-2c82f56b-83c6-40d3-b9f4-40a779497333.png)

**Comment by nedpals** [comment]
However, when I tried executing VLS in "child" mode (without crash reporting and etc), this is the result:
![Screenshot 2022-07-05 142532 on child](https://user-images.githubusercontent.com/7358345/177264787-7b171ac7-e46b-4a8c-a63e-88214f899085.png)

CPU utilization is low on standby and up to 6% if there's activity.

**Comment by nedpals** [comment]
@asampal Just a follow-up regarding your issue, this might have been fixed in https://github.com/vlang/vls/commit/7610a0a879b7ef6105412ef45474197ea6c4d85a please confirm. 

If not, please create a separate issue so that we can track it properly. Thanks :)

**Comment by asampal** [comment]
Thanks, @nedpals - this has resolved the problem wrt to high CPU and I/O for me as well.
