### ISSUE TITLE
Logs are written to $CWD/vls.log instead of language client log

### ISSUE THREAD

**Issue by yochem** [vlang/vls#366]
I'm using the current version of vls with NeoVim's LSP. This creates a `vls.log` file in my current working directory:

```
$ ls -A
.git/
.gitignore
v.mod
vls.log
z.v
```

This creates clutter in my source code folder. All other LSP logs can be found in the same file:  `~/.local/state/nvim/lsp.log`. Neovim also reports that this is the language server log file:

![image](https://user-images.githubusercontent.com/23235841/177536798-2d30909f-fdbc-44ed-b6ef-e032a5e3c81c.png)

It would be great if the vls logs can also be found in the same log file as any other lsp. Thank you in advance!

**Comment by SirZenith** [comment]
vls.log is VLS' server side log file. Now one can explicitly require VLS to generate this file by passing `--debug` flag to `vls` command.

Neovim's `:LspLog` command shows client side log. Normally it won't have much content in it. If you want to see complete debug output of VLS, you can run following command in Neovim:

```
:lua vim.lsp.set_log_level("debug")
```

**Comment by yochem** [comment]
Thanks for the explanation! Would it then be an idea to use a different location for the server logs instead of the current working directory? E.g., $XDG_DATA_HOME?

(I believe XDG_STATE_HOME is currently the recommendation for logs, but it is not much adopted yet)

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
