### ISSUE TITLE
VLS server never respawn after being randomly closed in VSCode

### ISSUE THREAD

**Issue by rilysh** [vlang/vls#370]
### V doctor
```
OS: linux, Devuan GNU/Linux 4 (chimaera)
Processor: 2 cpus, 64bit, little endian, Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz
CC version: cc (Debian 10.2.1-6) 10.2.1 20210110

getwd: /home/kiwimoe/Desktop/httptest
vmodules: /home/kiwimoe/.vmodules
vroot: /home/kiwimoe/Desktop/v
vexe: /home/kiwimoe/Desktop/v/v
vexe mtime: 2022-07-17 07:54:17
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 b4dedca

Git version: git version 2.30.2
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 827f7452
```

### VLS info 
```
vls version 0.0.1.bcbc46c
```

## Problem Description

After editing for certain times VLS automatically close the connection and with the output `Connection to server got closed. Server will restart.` But the server never restart until I manually do it. It's happening in every few minutes, therefore it's being impossible to use VLS

## Expected Output

VLS should reconnect after getting disconnect.

## Actual Output

[Info  - 10:19:58 PM] Connection to server got closed. Server will restart.
[Info  - 10:21:05 PM] VLS Version: 0.0.1.bcbc46c, OS: linux 64
[Info  - 10:21:05 PM] VLS executable path: /home/kiwimoe/.vls/bin/vls_linux_x64
[Info  - 10:21:05 PM] VLS build with V a4e0e0f
[Info  - 10:21:05 PM] Client / Editor: Visual Studio Code 1.69.1 (PID: 5639)
[Info  - 10:21:05 PM] Using V path (VROOT): /home/kiwimoe/Desktop/v
[Info  - 10:23:47 PM] Connection to server got closed. Server will restart.
[Info  - 10:23:47 PM] Connection to server got closed. Server will restart.

## Steps to Reproduce

Launch VSCode and start editing a V lang file for some time.
## Last Recorded LSP Requests

[vls.log](https://github.com/vlang/vls/files/9128192/vls.log)

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
