### ISSUE TITLE
VLS in vscode can not goto to definition when the v file  be placed in src directory

### ISSUE THREAD

**Issue by lydiandy** [vlang/vls#378]
### V doctor
```
OS: macos, macOS, 12.4, 21F79
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

getwd: /Users/xxx
vmodules: /Users/xxx/.vmodules
vroot: /Users/xxx/v/src
vexe: /Users/xxx/v/src/v
vexe mtime: 2022-08-15 21:44:50
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 9099594.3bc01d6

Git version: git version 2.32.1 (Apple Git-133)
Git vroot status: weekly.2022.33 (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20
```

### VLS info 
```
vls version 0.0.1.f890f35
```

## Problem Description
VLS in vscode can not goto to definition when the v file  be placed in src directory

## Expected Output
 VLS can goto definition just like v file in module root directory

## Actual Output
unknown function

**Comment by nedpals** [comment]
@lydiandy goto def in a file inside `src` works for me. do you mean that go to def'ing a module that uses the `src` folder does not work? because that might be possible

**Comment by nedpals** [comment]
your issue might be fixed https://github.com/vlang/vls/commit/8fb22447cd8877a3090c55150974dd36d869f223 but i will still fix the other one i meant since its indeed an issue

**Comment by lydiandy** [comment]
@nedpals I update the latest v and vls, the issue is not fixed. here is the example code:

![image](https://user-images.githubusercontent.com/56576373/185841597-4a3efe55-2046-4345-b7b3-53772df74c35.png)

main.v
```
module main

import m

fn main() {
	println(m.add_in_abc(1,2))
	println(m.add_in_def(2,3))
}
```
abc.v
```
module m

pub fn add_in_abc(x int, y int) int {
	return x+y
}
```
def.v
```
module m

pub fn add_in_def(x int,y int) int {
	return x+y
}
```
 goto definition works, when I move the abc.v and def.v into m directory.

**Comment by nedpals** [comment]
if thats the case, i have the fix already in place: https://github.com/vlang/vls/pull/383

i am still finalizing the rules on this but yeah the fix is already there 😅
