### ISSUE TITLE
vsCode can' t start vls when opening .v files without creating a workspace, can it be improved?

### ISSUE THREAD

**Issue by tzSharing** [vlang/vls#390]
vsCode can' t start vls when opening .v files without creating a workspace。
I'm not sure if it's a bug or a limitation of the editor itself, can it be improved?

**Comment by DJ-Dav** [comment]
i couldn't get vls to start, so i tried opening a workspace, but that caused the error:
command 'v.vls.restart' not found

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
