### ISSUE TITLE
Completion / Intellisense

### ISSUE THREAD

**Issue by nedpals** [vlang/vls#4]

**Comment by danieldaeschle** [comment]
https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/languageFeatures/completions.ts#L439

**Comment by danieldaeschle** [comment]
https://github.com/theia-ide/typescript-language-server/blob/a97834e2b8609fc7ca22663dec986640e01d0d31/server/src/lsp-server.ts#L427

**Comment by danieldaeschle** [comment]
this is really complicated.
