### ISSUE TITLE
V server don't work in CudaText LSP plugin

### ISSUE THREAD

**Issue by Alexey-T** [vlang/vls#401]
### V doctor
```
OS: linux, Ubuntu 20.04.5 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/user
vmodules: /home/user/.vmodules
vroot: /home/user/v
vexe: /home/user/v/v
vexe mtime: 2022-10-25 11:45:29
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 7660659

Git version: git version 2.25.1
Git vroot status: weekly.2022.43-1-g76606598
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### VLS info 
```
user@PC:~$ v ls --version
V 0.3.1 7660659
```

## Problem Description

CudaText (free editor, which has V lexer in Addons Manager), its LSP plugin, don't work with VLS.
How to configure LSP plugin, and what errors we see - 
https://github.com/CudaText-addons/cuda_lsp/issues/88

## Expected Output

VLS must give autocompletion.

## Actual Output

No autocompletion for file v/examples/mini_calculator.v .

## Steps to Reproduce

- Install CudaText on linux gtk2 x64
- In Addons Manager, install V lexer + LSP Client plugin
- Configure the LSP plugin - https://github.com/CudaText-addons/cuda_lsp/issues/88
- open in CudaText v/examples/mini_calculator.v
- call autocompletion with ctrl+space for some Id 

## Last Recorded LSP Requests

No vls.log.

**Comment by veksha** [comment]
it seems that VLS doesn't support `Content-Type` header!!
VLS is trying to parse it as JSON.
Can it be fixed, please?

**Comment by Alexey-T** [comment]
No work on it yet?

**Comment by veksha** [comment]
@SirZenith, if you have time, please look at this issue.
skipping "Content-Type" header (ignoring it) will be enough to make vls work in CudaText.

**Comment by SirZenith** [comment]
VLS should now work in CudaText, update to latest pre-release and have a try 😉.

**Comment by veksha** [comment]
@SirZenith unfortunately, it still gives same error: `ResponseError[-32700]: Invalid JSON.`

some questions/thoughts:
- are you testing with stdio or socket?
- did you forget to upload **all** changes?

i tried both approaches to build new vls:
- via `v ls --update --force`
- and cloning vls from repo and building it with `v run build.vsh gcc`

**Comment by SirZenith** [comment]
OK, I figure out how to start LSP on stdio. Yes the bug do persist. I'll be back to you soon.

**Comment by veksha** [comment]
```c
//"cmd_windows": ["v", "ls"],
"cmd_windows": ["v", "ls", "--socket"],
"tcp_port": 5007,
```

if I specify `cmd_*` (with "--socket") and `tcp_port` together, it must create process and connect to it's port, but it is not fully functional that way for some reason (maybe cuda_lsp plugin bug)

but if i leave only "tcp_port": 5007, line and run process externally (from Windows cmd console), then it is working ok! autocompletion (ctrl+space) works and diagnostics are reported..

**Comment by SirZenith** [comment]
My pull request is now merged, VLS should now works in stdio mode. Update to latest build and take a look, have a nice weekend.

**Comment by veksha** [comment]
thank you, @SirZenith!

now it kinda works.
I see autocompletion on empty line, but it can't complete "os.home" to "os.home_dir". is it normal?
also signatureHelp is not working,maybe something else...

**Comment by SirZenith** [comment]
@veksha 

> is it normal?

Yes, this is what LSP can do for now. Symbol generation still need some work I think.

Diagnostic currently only updades when `didSave` message is sent to server. It seems CudaText's LSP plugin doesn't send such message to server on file saved.

**Comment by veksha** [comment]
> Diagnostics currently only updades when `didSave` message is sent to server. It seems CudaText's LSP plugin doesn't send such message to server on file saved.

yes. because server must tell client that it has such capability. server responds with:
```json
"textDocumentSync": 2,
```
  in capabilities, but must have something like:
```json
"textDocumentSync": { "change": 2, "save": true },
```

from LSP spec:
```typescript
...

/**
* If present save notifications are sent to the server. If omitted the
* notification should not be sent.
*/
save?: boolean | SaveOptions;
```

**If omitted the notification should not be sent.**

(i guess a lot of editors (like vscode, sublime) are sending it anyway.)

@SirZenith should I open new issue for this? or can you quickly add `"save": true` to capabilities? if you agree with what i wrote above.

**Comment by SirZenith** [comment]
Yes, a new issue please. I think that is a more general improvement/fix, and make sense to have its own issue.

**Comment by veksha** [comment]
sorry, @SirZenith. I researched deeper and found out that
specifying "textDocumentSync" as a number is deprecated (since 3.x).
so in this case (for backwards compatibility) we must assume that server supports `didSave`.
Thanks for your time!

@Alexey-T this issue can be closed, I will prepare PR for cuda_lsp.
