### ISSUE TITLE
Text synchronization error on Windows.

### ISSUE THREAD

**Issue by SirZenith** [vlang/vls#423]
# Problem Description

On Windows, there are null character (`'\0'`) poping up in VLS' rope data structure after `textDocument/didChange` request.

For example:

![图片](https://user-images.githubusercontent.com/38665076/215127581-d49526d5-9c89-46e3-a2a2-605c28f5cc51.png)

On the right of above image shows, rope currently has only one node, contains 5737 characters, has no left or right chilid, and contains no null character in its content.

After adding a space on line 3, the only one rope node is split at inserting position, now rope is a tree of three node (with two leaves). And still, it has no null character in its content.

![图片](https://user-images.githubusercontent.com/38665076/215127795-8c83e46d-5184-442d-888b-97efaafdb2e1.png)

## Expected Behaviour

Keep on adding more space (or any other character) on line 3, all added character should be add to left leaf node of rope, and right leaf should remain the same.

## Actual Behaviour

![图片](https://user-images.githubusercontent.com/38665076/215129653-1a70ae8b-0dd8-4211-b197-923a7ce2fc4d.png)

Length of right leaf node remains unchanged, but null characters begain to show up in content of right leaf.

# Step to Reproduce

```
git clone https://github.com/SirZenith/vls.git
cd vls
git checkout windows-rope-bug
mkdir bin
v -g -gc boehm -cc msvc cmd/vls -o .\bin\vls
```

Now there should be a `vls.exe` under `bin` directory. Config your editor to use this binary as V language server, and make sure you can see language server's log message sended to your editor. In vscode, log message will appear in Output panel,

Find a file with more then 4096 characters but less then 8192 characters. Here you can use `structures/ropes/ropes.v` in VLS reop.

Type something, and check log message.

**Comment by SirZenith** [comment]
This possibly is a GC problem, when I change `-gc` flag to `boehm_incr`, result binary will behave slightly different.

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
