### ISSUE TITLE
README update for vls reports

### ISSUE THREAD

**Issue by yochem** [vlang/vls#437]
I see I forgot to update the README in #430. Currently:

> VLS generates a report and notifies the user by default when something is wrong. These crash reports are accessible which can be found inside C:\Users\<user_name\.vls\reports for Windows and ~/.vls/reports for both Linux and MacOS. The contents of the file can be then pasted into the [issue tracker form](https://github.com/vlang/vls/issues/new).

Do we want to just state that it is in `os.cache_dir()/vls/reports` or name the paths for windows and linux/macos?

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
