### ISSUE TITLE
now use vls or v-analyzer

### ISSUE THREAD

**Issue by iskylite** [vlang/vls#454]
i see below warnning in README
![image](https://github.com/vlang/vls/assets/39998834/51382847-9040-4608-8231-cf26c01b897d)

but about tell me v-analyzer is for old V version.
![image](https://github.com/vlang/vls/assets/39998834/2419e07d-3651-4601-8c38-65e65b68a3ff)

so which ls is right?

**Comment by JalonSolov** [comment]
No matter what it says, `v-analyzer` is the current, most up-to-date, and most correct.

vls is, essentially, dead.  That's why the `Warning` was added at the top of the README.

**Comment by JalonSolov** [comment]
Yes, the phrasing could be more explicit.
