### ISSUE TITLE
code window is asked to be reloaded when vls runs for a long time

### ISSUE THREAD

**Issue by Delta456** [vlang/vls#47]
If VLS is running for long then sometimes it makes the editor to hang and then asks for user to reload the window.

**Comment by nedpals** [comment]
can u state here what editor and os are u using? as well as instructions that we can use to reproduce that issue 🙂

**Comment by Delta456** [comment]
I am using the V compiler and my OS was Windows 10. I had to write bad code for VLS to detect then fix it afterwards then when doing `make` on the issues trigger sometimes.
