### ISSUE TITLE
Check for structs/functions in other files

### ISSUE THREAD

**Issue by matteoturini** [vlang/vls#49]

**Comment by nedpals** [comment]
Closed. Duplicate of #11.

**Comment by nedpals** [comment]
Sorry bout that. Will add support for checking symbols in other (unopened) files

**Comment by matteoturini** [comment]
Oh, so it checks on opened files?

**Comment by nedpals** [comment]
Yes.

**Comment by matteoturini** [comment]
Is this feature near implementation? Any updates?

**Comment by nedpals** [comment]
@matteoturini Yes and I forgot to close this. It is fixed in https://github.com/vlang/vls/commit/9bbad7d39a49e26b55d6249c7a2e6155b87ae162
