### ISSUE TITLE
Don't panic on code errors

### ISSUE THREAD

**Issue by matteoturini** [vlang/vls#50]

**Comment by nedpals** [comment]
Can you please provide the editor you are using, the operating system, and any additional details that may help in addressing your problem?

**Comment by matteoturini** [comment]
VSCode, Windows 10 x64, master branch

**Comment by Zymlex** [comment]
I also encountered this problem, vls crashes and require restart VSCode

**Comment by matteoturini** [comment]
> I also encountered this problem, vls crashes and require restart VSCode

You can actually reload the window. CTRL + SHIFT + P > "Reload Window"
