### ISSUE TITLE
Check compatibility with Qt Creator

### ISSUE THREAD

**Issue by Zymlex** [vlang/vls#53]
![изображение](https://user-images.githubusercontent.com/25817412/103453929-98a75380-4d2a-11eb-8b80-cee6b31a77a7.png)
![изображение](https://user-images.githubusercontent.com/25817412/103454046-ac06ee80-4d2b-11eb-85cb-4d3a644a5d95.png)

**Comment by JalonSolov** [comment]
Try https://blog.vosca.dev/meet-v-analyzer/ instead, now that it is released.
