### ISSUE TITLE
formatter incorrectly removes lines

### ISSUE THREAD

**Issue by JalonSolov** [vlang/vls#54]
I have a file named `decbin.v`:
```v
fn decbin(n u64) string {
    mut s := ''
    mut u := n

    for u > 0 {
        s += if u & 1 == 1 { '1' } else { '0'}
        u = u >> 1
    }

    return s.reverse()
}

println(decbin(7))
println(decbin(64))
println(decbin(-4))
```
When this file is saved, the 3 `println` lines at the end (plus the blank line above them) are stripped from the file.  Not good.

Perfectly valid V file, runs fine as-is.

**Comment by nedpals** [comment]
@JalonSolov has this issue been fixed for you? I've tried it and works fine for me at my side.

**Comment by yuyi98** [comment]
It's ok now.
