### ISSUE TITLE
Document outline is ordered alphabetically and not as in the code

### ISSUE THREAD

**Issue by serkonda7** [vlang/vls#59]
Take for example the first part of the outline for `fmt.v`. All entries are sorted in alphabetical order and not as they show up in the actual file.
This is a lot harder to use for developers that are somewhat familiar with the source and doesn't help newcomers to get there.
![image](https://user-images.githubusercontent.com/40118727/104594907-1f84f600-5672-11eb-87f3-a2c28a651a96.png)

**Comment by nedpals** [comment]
@serkonda7 AFAIK VLS does not sort it by default as seen on here: https://github.com/vlang/vls/blob/ba5c969ffb69e14ea4548f4ddbb828d3ae58b8c0/tests/features_test.v#L109 

It might be VSCode sorted the symbols in alphabetical order. You can change the setting by clicking the three dots menu on the Outline pane:

![Screenshot from 2021-01-14 21-34-04](https://user-images.githubusercontent.com/7358345/104597579-75788e80-56b0-11eb-8ce5-06833bb20f52.png)

**Comment by serkonda7** [comment]
Thanks, I did not knew about this.
