### ISSUE TITLE
Don't report non-main module error

### ISSUE THREAD

**Issue by zakuro9715** [vlang/vls#60]
When develop submodule, this `project must include a main module` error is showed. It should be disabled

[![Image from Gyazo](https://i.gyazo.com/5fb93c17ee3fd62d45d0fa3ca840ba02.png)](https://gyazo.com/5fb93c17ee3fd62d45d0fa3ca840ba02)

**Comment by nedpals** [comment]
Closed. Fixed in https://github.com/vlang/vls/commit/7c93bf3ac7682d0a95005edfbcba75d4e41a6470.
