### ISSUE TITLE
function `strings.new_builder` is private'

### ISSUE THREAD

**Issue by zakuro9715** [vlang/vls#87]
[![Image from Gyazo](https://i.gyazo.com/f19f8c3ff1c71056f049e56f6ad92dc3.png)](https://gyazo.com/f19f8c3ff1c71056f049e56f6ad92dc3)

`table.new_table` and `time.new_timer` are same

I guess `xxx.new_xxx` is treated as private

**Comment by nedpals** [comment]
The offending code is found here: `vlib/v/checker/checker.v` at line 1924. I'm not sure what criteria on the if statement made it go to that path

**Comment by nedpals** [comment]
Closed. Should be fixed on the latest version of VLS.
