### ISSUE TITLE
VLS get_type_symbol invalid type

### ISSUE THREAD

**Issue by alextwothousand** [vlang/vls#88]
Opened up vscodium.
```
[Info  - 15:36:01] VLS Version: 0.0.1, OS: windows 64
[Info  - 15:36:01] Client / Editor: VSCodium 1.54.3
V panic: get_type_symbol: invalid type (typ=0 idx=0). Compiler bug. This should never happen. Please create a GitHub issue.

print_backtrace_skipping_top_frames is not implemented
[Error - 15:36:02] Connection to server is erroring. Shutting down server.
[Error - 15:36:02] Connection to server is erroring. Shutting down server.
[Error - 15:36:02] Connection to server is erroring. Shutting down server.
[Error - 15:36:02] Connection to server is erroring. Shutting down server.
[Error - 15:36:02] Connection to server is erroring. Shutting down server.
```

Output of `v version`
```
V 0.2.2 92f19f5
```

**Comment by Delta456** [comment]
What code had you opened when you were trying to use `vls`?

**Comment by alextwothousand** [comment]
A fresh project with a lot of Win API interaction.
Do you need a code sample?

**Comment by alextwothousand** [comment]
```v
module main

#flag windows -DWIN32_LEAN_AND_MEAN
#include <windows.h>

type HWND = voidptr
type DWORD = u32

type WPARAM = u64
type LPARAM = i64

type LONG = int
type UINT = u32

// https://docs.microsoft.com/en-us/windows/win32/api/windef/ns-windef-point
struct POINT {
	mut:
	x LONG
	y LONG
}

// https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-msg
struct MSG {
	mut:
	hwnd 		HWND
	message 	DWORD
	wParam 		WPARAM
	lParam 		LPARAM
	time		DWORD
	pt			POINT
	lPrivate 	DWORD
}

// BOOL RegisterHotKey(HWND hWnd, int  id, UINT fsModifiers, UINT vk);
fn C.RegisterHotKey(HWND, int, UINT, UINT) bool

// BOOL GetMessage(LPMSG lpMsg, HWND  hWnd, UINT  wMsgFilterMin, UINT  wMsgFilterMax);
fn C.GetMessage(MSG, HWND, UINT, UINT) bool

// void * memset ( void * ptr, int value, size_t num );
fn C.memset(voidptr, int, size_t) voidptr

fn main() {
	if !C.RegisterHotKey(C.NULL, 1, C.MOD_ALT, `b`) {
		println("Register Hotkey is invalid")
		return
	}

	msg := MSG{}

	for !C.GetMessage(&msg, C.NULL, 0, 0) {
		if msg.message != C.WM_HOTKEY {
			continue
		}

		println("Hotkey clicked!")
	}
}
```

**Comment by nedpals** [comment]
This and #89 is really hard to debug where to locate the offending function without the backtraces implemented other than TCC. 

@alextwothousand can you try recompile it without `-prod`? Thanks

**Comment by alextwothousand** [comment]
> This and #89 are really hard to debug where to locate the offending function without the backtraces implemented other than TCC. 
> 
> 
> 
> @alextwothousand can you try recompile VLS without `-prod`? Thanks

I wasn't explicitly compiling with `-prod`.

Here is what I was doing to compile my program.

```
v -cc msvc main.v
```

**Comment by nedpals** [comment]
@alextwothousand I see. Can you recompile VLS using TCC (without specifying `-prod` or `-cc` flags) then? I meant that because compiling programs using the TCC compiler can produce backtraces and it's the only supported right now in V. I want to find out what made the VLS to trigger the `get_type_symbol` panic.

**Comment by alextwothousand** [comment]
I will give this a go at the earliest convenience.

**Comment by nedpals** [comment]
@alextwothousand It might be a Windows issue but the above code works fine on Linux. 
@danieldaeschle If you have the time, can you diagnose this issue?

**Comment by alextwothousand** [comment]
I can attempt to try it in Linux? What distribution are you running— just for reference?

**Comment by nedpals** [comment]
> I can attempt to try it in Linux? What distribution are you running— just for reference?
> 
> The fact that it's a Windows only issue is... interesting.

It is. My distro is Ubuntu 20.04 64-bit

**Comment by alextwothousand** [comment]
> > I can attempt to try it in Linux? What distribution are you running— just for reference?
> 
> > 
> 
> > The fact that it's a Windows only issue is... interesting.
> 
> 
> 
> It is interesting. My distro is Ubuntu 20.04 64-bit

OK. I will attempt to reproduce this either on Fedora or Arch.

**Comment by nedpals** [comment]
Closing this as it is not applicable anymore to the current version of VLS.
