### ISSUE TITLE
vls uses >80% ram (of 8GB)

### ISSUE THREAD

**Issue by Apppppppple** [vlang/vls#92]
using this test file:
```v
import gg
fn main()
{
  gg.
}
```
If I trigger autocomplete on the `gg.` the vls ram usage quickly balloons and freezes the system until I `sysrq+f`.
I'm using nvim-lspconfig instead of vscode but I don't think that should change too much.

**Comment by nedpals** [comment]
@Apppppppple I feel you and our team has been working on improving the memory management section. We will be also releasing a new version of VLS with Boehm GC enabled soon in order to lessen the problems with it (in the meantime).

**Comment by medvednikov** [comment]
GC or not, I think the server shouldn't allocate so much RAM in the first place :)

**Comment by medvednikov** [comment]
v -gc boehm

**Comment by Apppppppple** [comment]
> v -gc boehm
Thanks! Still seems to freeze system though unfortunately and boehm_full gets to ~70% then crashes.
Is there a way I could contribute to vls? I'm not a very good programmer but v seems quite cool and I'd like to help if I can.

**Comment by Apppppppple** [comment]
My bad - didn't realize I was supposed to compile with `-manualfree` and that resolved pretty much all of the mem problems. Autocomplete seems to crash after the first time I use it though.

**Comment by nedpals** [comment]
@Apppppppple with or without explicitly adding `-manualfree` flag, it is enabled by default. Maybe it crashes often hence the memory reductions. I will reopen this issue until it is resolved.

**Comment by Apppppppple** [comment]
@nedpals I guess that's possible but I don't think neovim restarts lsps - before when it crashed it would stay dead, and in general you need to reload the buffer to reattach lsp servers. All I know is something about `v -prod cmd/vls -manualfree -gc boehm_incr -manualfree -cc clang -m64 -compress` reduced the memory usage drastically (and I don't think it's just the boehm_incr because I had tested that before without much success)

**Comment by nedpals** [comment]
> GC or not, I think the server shouldn't allocate so much RAM in the first place :)

That's true :) And it's a challenge that I'm hoping to accomplish

**Comment by Apppppppple** [comment]
> That's interesting. Would you mine share the memory usage here?

It's around 0.9% at idle to ~1.5% when importing a module (which afaik is what triggered it before). I thought I remembered seeing relatively high cpu usage (maybe 15-20%) when I first compiled it like this, but I can't reproduce that and it's at ~0.1% right now.

**Comment by Apppppppple** [comment]
> @\nedpals I guess that's possible but I don't think neovim restarts lsps - before when it crashed it would stay dead, and in general you need to reload the buffer to reattach lsp servers. All I know is something about `v -prod cmd/vls -manualfree -gc boehm_incr -manualfree -cc clang -m64 -compress` reduced the memory usage drastically (and I don't think it's just the boehm_incr because I had tested that before without much success)

Nevermind that, sorry. I recompiled with just `v -prod -gc boehm_incr` and I'm getting practically the same results. I'm pretty sure the problem all along was that my editor would always put in the text for the currently selected autocomplete, and then that would spam the lsp with completion and textchanged requests which was causing the ram usage and slowdown. The time I compiled vls with  the `-manualfree` stuff was pretty much the same time that I fixed the completion to not spam the lsp, so I don't think the compilation flags were actually causing the differences.

**Comment by Apppppppple** [comment]
Should I close this issue now?

**Comment by nedpals** [comment]
@Apppppppple We'll just close it once the issue has been fully resolved. Still in progress atm
